### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by BoredManCodes** [vremes/shrpy#37]
Hiya, fairly sure I've done all the steps correctly but when trying to post images I'm getting 500 errors and the following log
```
2022-01-28 11:10:29,797 | app.log_exception | ERROR | Exception on /api/upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/www/shrpy/app/core/utils.py", line 45, in decorated_function
    return f(*args, **kwargs)
  File "/var/www/shrpy/app/blueprints/api.py", line 18, in upload
    return FileService.create()
  File "/var/www/shrpy/app/core/services.py", line 37, in create
    hmac_hash = create_hmac_hash(f.filename, current_app.secret_key)
  File "/var/www/shrpy/app/core/utils.py", line 74, in create_hmac_hash
    hmac_secret_key.encode('utf-8'),
AttributeError: 'NoneType' object has no attribute 'encode'
```

Any help is appreciated

**Comment by vremes** [comment]
Hey there,

To me it looks like `current_app.secret` key is `None`.

Did you set a value for `FLASK_SECRET` on your `.env` file?

Example (`/var/www/shrpy/.env`):
```dotenv
FLASK_SECRET = "my-secret-string-here"
```

**Comment by BoredManCodes** [comment]
I'll make a new one now but it was set to
FLASK_SECRET = "c355d05a326de2ea8a091512dcb235c3c9b7e2ec9cacd65c1d7368e22d8a6d6a"

**Comment by vremes** [comment]
Hey,

That looks okay to me.

Can you double check and make sure you have set the value for `FLASK_SECRET` on `.env`, not `.env-example` file?

**Comment by BoredManCodes** [comment]
Was one of the first things I checked, and just checked again

**Comment by vremes** [comment]
Hey again,

Do you have already existing `FLASK_SECRET` environment variable on your system which could overlap with the `.env` file?

You can use the following command on Linux to list and filter env variables which include "FLASK":
```sh
printenv | grep "FLASK"
```

**Comment by BoredManCodes** [comment]
No output
```
root@singapoor:~# printenv | grep "FLASK"
root@singapoor:~# 
```

**Comment by vremes** [comment]
Hey,

Could you restart gunicorn and then check if the same issue with file uploading still occurs?

You can restart it using the following command:
```
supervisorctl restart shrpy
````

**Comment by BoredManCodes** [comment]
You legend, that fixed it. <3
